### ISSUE TITLE
Невозможность работы программы с 18-ти значными картами

### ISSUE THREAD

**Issue by Sempela23** [Nef1lim23/java1#1]
Шаги для воспроизведения

- Загрузить IntelliJ IDEA
- Создать файл и загрузить код
- Взять с сайта https://www.freeformatter.com/credit-card-number-generator-validator.html 18-ти значный номер
- Вставить этот номер в четвёртую строку внутри " " (ковычек)  написанного ранее кода

Нажать слева перед первой строкой нашего кода, кнопку в виде зеленого треугольника "Run Main" ,  так же в меню есть кнопка "Run" , нужно нажать на нее и там откроется выпадающий список и выбрать "Run (название класса)"  или сочетанием клавиш Shift + F10

Ожидаемый результат:

Компилятор выведет сообщение " Result is OK"

Фактический результат:

Компилятор вывел сообщение "Result is FAIL"

Скриншоты ошибок:
![image](https://user-images.githubusercontent.com/56215877/130256012-4aa98af9-7197-444e-a5ec-330e0ff07527.png)

![image](https://user-images.githubusercontent.com/56215877/130256129-69081300-3e0f-4f45-8d76-790d6622fc7c.png)

Окружение: 
Win 10 pro x64
Java v11.0.12
IntelliJ IDEA
Яндекс Браузер

**Comment by Nef1lim23** [comment]
> Шаги для воспроизведения
> 
> * Загрузить IntelliJ IDEA
> * Создать файл и загрузить код
> * Взять с сайта https://www.freeformatter.com/credit-card-number-generator-validator.html 18-ти значный номер
> * Вставить этот номер в четвёртую строку внутри " " (ковычек)  написанного ранее кода
> 
> Нажать слева перед первой строкой нашего кода, кнопку в виде зеленого треугольника "Run Main" , так же в меню есть кнопка "Run" , нужно нажать на нее и там откроется выпадающий список и выбрать "Run (название класса)" или сочетанием клавиш Shift + F10
> 
> Ожидаемый результат:
> 
> Компилятор выведет сообщение " Result is OK"
> 
> Фактический результат:
> 
> Компилятор вывел сообщение "Result is FAIL"
> 
> Скриншоты ошибок:
> ![image](https://user-images.githubusercontent.com/56215877/130256012-4aa98af9-7197-444e-a5ec-330e0ff07527.png)
> 
> ![image](https://user-images.githubusercontent.com/56215877/130256129-69081300-3e0f-4f45-8d76-790d6622fc7c.png)
> 
> Окружение:
> Win 10 pro x64
> Java v11.0.12
> IntelliJ IDEA
> Яндекс Браузер
